# Generated by Django 2.1.2 on 2018-11-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('something', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('lastname', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=64, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'человек',
                'verbose_name_plural': 'люди',
            },
        ),
    ]
