# Generated by Django 2.1.2 on 2018-11-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('something', '0004_auto_20181129_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
    ]
