# Generated by Django 2.1.2 on 2018-11-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('something', '0005_remove_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='urlDownload',
            field=models.CharField(blank=True, default=None, max_length=36, null=True),
        ),
    ]
