# Generated by Django 2.1.2 on 2018-11-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('something', '0007_uploadfile_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='upload',
            field=models.FileField(upload_to='media/'),
        ),
    ]
